# Generated by Django 5.0.1 on 2024-12-29 03:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='date_of_booking',
            new_name='checkOut',
        ),
        migrations.AddField(
            model_name='reservation',
            name='checkIn',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
