# Generated by Django 5.0.1 on 2025-01-27 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0005_alter_reservation_guest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='reservation',
            new_name='reservations',
        ),
    ]
